language: python
python:
  - "3.6"

dist: trusty
sudo: false

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coverage

script:
  - coverage run -m pytest

after_success:
  - pip install codecov
  - codecov
