name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Update apt index
        run: sudo apt-get update
      - name: Install apt packages
        run: sudo apt-get install -y -q dh-autoreconf build-essential libarchive-dev squashfs-tools
      - name: Install node
        shell: bash -l {0}
        run: |
          nvm install 12.13.1
          nvm use 12.13.1
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          python -m pipenv install --dev
      - run: npm install

      - run: npm test
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Report code coverage
        run: |
          python -m pip install codecov
          codecov
