name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Update apt index
        run: sudo apt-get update
      - name: Install apt packages
        run: sudo apt-get install -y -q dh-autoreconf build-essential libarchive-dev squashfs-tools
      - name: Install node
        shell: bash -l {0}
        run: |
          nvm install 16.16.0
          nvm use 16.16.0
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          python -m pipenv install --dev
      - run: npm install

      - run: npm test
      - name: Test with pytest
        run: |
          python -m pipenv run python -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
